version: '2'

services:
  mongodb:
    image: bitnami/mongodb:5.0.14
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=mongo
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=mongo
      - MONGODB_DATABASE=quanlysieuthidienthoai
    volumes:
      - './mongo-backup:/bitnami/mongodb'
