version: '2.1'

services:
  mysql:
    image: bitnami/mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - './postgres-backup:/bitnami/mysql/data'
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=1234
#      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6
